import NonlinearDynamics.Random.RandomCocycles.InfiniteHopfMaximal
import Mathlib.Analysis.InnerProductSpace.MeanErgodic
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Function.ConvergenceInMeasure
import Mathlib.MeasureTheory.Function.LpSpace.Complete
import Mathlib.MeasureTheory.Function.SimpleFuncDenseLp

/-!
# Koopman L2 mean convergence and a dense pointwise-good core

This module builds the Hilbert-space layer needed between the weak maximal
estimate in `InfiniteHopfMaximal` and a future pointwise Birkhoff theorem.  A
measure-preserving map acts on real `L²` by Koopman composition.  Mathlib's
von Neumann mean-ergodic theorem makes its finite averages converge in `L²` to
the orthogonal projection onto the fixed subspace.

The proof keeps mean convergence distinct from pointwise convergence.  It
first proves a raw pointwise telescoping theorem for bounded coboundaries,
then shows that fixed vectors plus coboundaries generated by `L²` simple
functions form a dense set.  The final representative bridge identifies this
dense set as almost everywhere pointwise-good for Birkhoff averages.

Measure preservation is the only measure-theoretic assumption.  Finite total
mass, probability normalization, ergodicity, injectivity, surjectivity, and
invertibility are not required.  The exponent two is essential to the
orthogonal-projection argument.  No `L¹` density transfer, full pointwise
Birkhoff theorem, conditional-expectation identification, ergodic constant
limit, Kingman theorem, Lyapunov exponent, or Oseledets splitting is proved.
-/

open MeasureTheory Set Filter Function
open scoped ENNReal Topology

noncomputable section

namespace NonlinearDynamics.Random.RandomCocycles

universe uΩ

variable {Ω : Type uΩ} [MeasurableSpace Ω]
  {T : Ω → Ω} {μ : Measure Ω}

omit [MeasurableSpace Ω] in
/-- The average of a forward coboundary telescopes to its two endpoint values.
This is raw finite-orbit algebra and needs no measurability or measure.  At
`n = 0`, the inverse is totalized and both sides are zero. -/
theorem birkhoffAverage_forwardCoboundary (u : Ω → ℝ)
    (n : ℕ) (ω : Ω) :
    birkhoffAverage ℝ T (fun x ↦ u (T x) - u x) n ω =
      (n : ℝ)⁻¹ • (u (T^[n] ω) - u ω) := by
  calc
    birkhoffAverage ℝ T (fun x ↦ u (T x) - u x) n ω =
        birkhoffAverage ℝ T u n (T ω) -
          birkhoffAverage ℝ T u n ω := by
      simp only [birkhoffAverage, birkhoffSum, Finset.sum_sub_distrib,
        smul_sub]
      have hsum :
          (∑ j ∈ Finset.range n, u (T (T^[j] ω))) =
            ∑ j ∈ Finset.range n, u (T^[j] (T ω)) := by
        apply Finset.sum_congr rfl
        intro j _hj
        rw [← Function.iterate_succ_apply' (f := T) j ω,
          ← Function.iterate_succ_apply (f := T) j ω]
      rw [hsum]
    _ = (n : ℝ)⁻¹ • (u (T^[n] ω) - u ω) :=
      birkhoffAverage_apply_sub_birkhoffAverage (R := ℝ) T u n ω

omit [MeasurableSpace Ω] in
/-- Every forward coboundary generated by a bounded real potential has
pointwise Birkhoff averages converging to zero. -/
theorem tendsto_birkhoffAverage_forwardCoboundary (u : Ω → ℝ)
    (hu : Bornology.IsBounded (Set.range u)) (ω : Ω) :
    Tendsto (fun n ↦ birkhoffAverage ℝ T
      (fun x ↦ u (T x) - u x) n ω) atTop (nhds 0) := by
  apply (tendsto_birkhoffAverage_apply_sub_birkhoffAverage
    ℝ (f := T) (g := u) (x := ω)
      (hu.subset (Set.range_comp_subset_range
        (fun n ↦ T^[n] ω) u))).congr'
  exact Eventually.of_forall fun n ↦ by
    calc
      birkhoffAverage ℝ T u n (T ω) -
          birkhoffAverage ℝ T u n ω =
          (n : ℝ)⁻¹ • (u (T^[n] ω) - u ω) :=
        birkhoffAverage_apply_sub_birkhoffAverage (R := ℝ) T u n ω
      _ = birkhoffAverage ℝ T
          (fun x ↦ u (T x) - u x) n ω :=
        (birkhoffAverage_forwardCoboundary u n ω).symm

private theorem fixedOrthogonal_le_closure_range_sub_one
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [CompleteSpace E] (L : E →L[ℝ] E) (hL : ‖L‖ ≤ 1) :
    (L.eqLocus (1 : E →L[ℝ] E))ᗮ ≤
      (LinearMap.range ((L : E →ₗ[ℝ] E) - 1)).topologicalClosure := by
  rw [← Submodule.orthogonal_orthogonal_eq_closure]
  refine Submodule.orthogonal_le fun x hx ↦
    eq_of_norm_le_re_inner_eq_norm_sq (𝕜 := ℝ) ?_ ?_
  · simpa using L.le_of_opNorm_le hL x
  · have hinner : ∀ y, inner ℝ (L y) x = inner ℝ y x := by
      simpa [Submodule.mem_orthogonal, inner_sub_left, sub_eq_zero] using hx
    simp [hinner]

/-- The real Koopman composition operator on `L²`. -/
def koopmanL2 (hT : MeasurePreserving T μ μ) :
    Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ :=
  (Lp.compMeasurePreservingₗᵢ ℝ T hT).toContinuousLinearMap

/-- The closed real `L²` subspace fixed by Koopman composition. -/
def koopmanFixedSubspaceL2 (hT : MeasurePreserving T μ μ) :
    Submodule ℝ (Lp ℝ 2 μ) :=
  (koopmanL2 hT).eqLocus (1 : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ)

/-- Orthogonal projection onto the Koopman-fixed real `L²` subspace. -/
def koopmanInvariantProjectionL2 (hT : MeasurePreserving T μ μ) :
    Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ :=
  ((koopmanL2 hT).eqLocus
    (1 : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ)).starProjection

/-- The forward real `L²` coboundary operator `U_T - I`. -/
def koopmanCoboundaryL2 (hT : MeasurePreserving T μ μ) :
    Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ :=
  koopmanL2 hT - 1

/-- Koopman coboundaries whose generating `L²` vectors are represented by
simple functions. -/
def simpleKoopmanCoboundarySetL2 (hT : MeasurePreserving T μ μ) :
    Set (Lp ℝ 2 μ) :=
  koopmanCoboundaryL2 hT '' (Lp.simpleFunc ℝ 2 μ : Set (Lp ℝ 2 μ))

/-- Sums of Koopman-fixed `L²` vectors and simple-function coboundaries. -/
def fixedPlusSimpleCoboundarySetL2 (hT : MeasurePreserving T μ μ) :
    Set (Lp ℝ 2 μ) :=
  {f | ∃ h ∈ koopmanFixedSubspaceL2 hT,
    ∃ c ∈ simpleKoopmanCoboundarySetL2 hT, f = h + c}

/-- Applying the project Koopman operator is Mathlib's
measure-preserving `Lp` composition. -/
@[simp] theorem koopmanL2_apply (hT : MeasurePreserving T μ μ)
    (f : Lp ℝ 2 μ) :
    koopmanL2 hT f = Lp.compMeasurePreserving T hT f :=
  rfl

/-- Iterating the Koopman operator agrees with composition by the
corresponding iterate of the base map. -/
theorem iterate_koopmanL2_apply (hT : MeasurePreserving T μ μ)
    (n : ℕ) (f : Lp ℝ 2 μ) :
    (koopmanL2 hT)^[n] f =
      Lp.compMeasurePreserving (T^[n]) (hT.iterate n) f := by
  change (Lp.compMeasurePreserving T hT)^[n] f = _
  rw [Lp.compMeasurePreserving_iterate]

/-- The Koopman continuous linear map is a contraction.  The inequality is
kept instead of unconditional norm equality so the zero-measure space remains
honest. -/
theorem norm_koopmanL2_le (hT : MeasurePreserving T μ μ) :
    ‖koopmanL2 hT‖ ≤ 1 := by
  change ‖(Lp.compMeasurePreservingₗᵢ (E := ℝ) (p := (2 : ℝ≥0∞))
    ℝ T hT).toContinuousLinearMap‖ ≤ 1
  exact LinearIsometry.norm_toContinuousLinearMap_le _

/-- The orthogonal complement of the fixed subspace lies in the closed range
of the Koopman coboundary operator. -/
theorem fixedOrthogonal_le_closure_range_koopmanL2
    (hT : MeasurePreserving T μ μ) :
    (koopmanFixedSubspaceL2 hT)ᗮ ≤
      (LinearMap.range
        ((koopmanCoboundaryL2 hT : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ) :
          Lp ℝ 2 μ →ₗ[ℝ] Lp ℝ 2 μ)).topologicalClosure := by
  change (koopmanFixedSubspaceL2 hT)ᗮ ≤
    (LinearMap.range
      (((koopmanL2 hT : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ) :
        Lp ℝ 2 μ →ₗ[ℝ] Lp ℝ 2 μ) - 1)).topologicalClosure
  exact fixedOrthogonal_le_closure_range_sub_one (koopmanL2 hT)
    (norm_koopmanL2_le hT)

/-- Simple-function Koopman coboundaries are dense enough to approximate
every vector orthogonal to the fixed subspace. -/
theorem fixedOrthogonal_subset_closure_simpleKoopmanCoboundarySetL2
    (hT : MeasurePreserving T μ μ) :
    ((koopmanFixedSubspaceL2 hT)ᗮ : Set (Lp ℝ 2 μ)) ⊆
      closure (simpleKoopmanCoboundarySetL2 hT) := by
  intro f hf
  have hf' := fixedOrthogonal_le_closure_range_koopmanL2 hT hf
  change f ∈ closure (Set.range (koopmanCoboundaryL2 hT)) at hf'
  apply (closure_minimal ?_ isClosed_closure) hf'
  exact (koopmanCoboundaryL2 hT).continuous.range_subset_closure_image_dense
    (Lp.simpleFunc.dense (E := ℝ) (p := (2 : ℝ≥0∞)) (μ := μ) (by simp))

/-- Fixed vectors plus simple-function Koopman coboundaries form a dense
subset of real `L²`. -/
theorem dense_fixedPlusSimpleCoboundarySetL2
    (hT : MeasurePreserving T μ μ) :
    Dense (fixedPlusSimpleCoboundarySetL2 hT) := by
  rw [dense_iff_closure_eq]
  apply eq_univ_of_forall
  intro f
  let K := (koopmanL2 hT).eqLocus
    (1 : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ)
  let p : Lp ℝ 2 μ := K.starProjection f
  let r : Lp ℝ 2 μ := f - p
  have hp : p ∈ koopmanFixedSubspaceL2 hT := by
    change K.starProjection f ∈ K
    exact (K.orthogonalProjectionOnto f).2
  have hrOrth : r ∈ Kᗮ := by
    exact K.sub_starProjection_mem_orthogonal f
  have hrClosure : r ∈ closure (simpleKoopmanCoboundarySetL2 hT) := by
    apply fixedOrthogonal_subset_closure_simpleKoopmanCoboundarySetL2 hT
    exact hrOrth
  have himage : f ∈ closure
      ((fun c : Lp ℝ 2 μ ↦ p + c) ''
        simpleKoopmanCoboundarySetL2 hT) := by
    have hcont : Continuous (fun c : Lp ℝ 2 μ ↦ p + c) :=
      continuous_const.add continuous_id
    have hmem := mem_closure_image hcont.continuousAt hrClosure
    simpa only [p, r, add_sub_cancel] using hmem
  apply (closure_mono ?_) himage
  rintro _ ⟨c, hc, rfl⟩
  exact ⟨p, hp, c, hc, rfl⟩

/-- Von Neumann mean convergence for the project Koopman operator, with the
limit written as Mathlib's bundled orthogonal projection. -/
theorem tendsto_birkhoffAverage_koopmanL2
    (hT : MeasurePreserving T μ μ) (f : Lp ℝ 2 μ) :
    Tendsto (birkhoffAverage ℝ (koopmanL2 hT) id · f) atTop
      (nhds (((koopmanL2 hT).eqLocus
        (1 : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ)).orthogonalProjectionOnto f)) := by
  exact (koopmanL2 hT).tendsto_birkhoffAverage_orthogonalProjection
    (norm_koopmanL2_le hT) f

/-- Von Neumann mean convergence with the limit named by the project
invariant projection. -/
theorem tendsto_birkhoffAverage_koopmanL2_projection
    (hT : MeasurePreserving T μ μ) (f : Lp ℝ 2 μ) :
    Tendsto (birkhoffAverage ℝ (koopmanL2 hT) id · f) atTop
      (nhds (koopmanInvariantProjectionL2 hT f)) := by
  simpa only [koopmanInvariantProjectionL2, koopmanFixedSubspaceL2,
    Submodule.starProjection_apply] using
      tendsto_birkhoffAverage_koopmanL2 hT f

/-- `L²` mean convergence supplies a strictly increasing subsequence whose
chosen representatives converge almost everywhere to the chosen representative
of the invariant projection.  This is the general pointwise consequence of
the norm theorem used here; it does not assert convergence of the full
sequence. -/
theorem exists_subsequence_ae_tendsto_birkhoffAverage_koopmanL2_projection
    (hT : MeasurePreserving T μ μ) (f : Lp ℝ 2 μ) :
    ∃ ns : ℕ → ℕ, StrictMono ns ∧
      ∀ᵐ ω ∂μ, Tendsto
        (fun i ↦ (birkhoffAverage ℝ (koopmanL2 hT) id (ns i) f) ω)
        atTop (nhds (koopmanInvariantProjectionL2 hT f ω)) := by
  have hmean := tendsto_birkhoffAverage_koopmanL2_projection hT f
  have hmeasure := tendstoInMeasure_of_tendsto_Lp hmean
  exact hmeasure.exists_seq_tendsto_ae

/-- A Koopman-fixed `L²` vector has a chosen representative whose Birkhoff
averages converge almost everywhere.  The proof intersects the representative
equalities for every natural iterate; equality in `L²` alone is not treated as
pointwise equality. -/
theorem ae_mem_birkhoffConvergenceSet_of_mem_koopmanFixedSubspaceL2
    (hT : MeasurePreserving T μ μ) {h : Lp ℝ 2 μ}
    (hh : h ∈ koopmanFixedSubspaceL2 hT) :
    ∀ᵐ ω ∂μ, ω ∈ birkhoffConvergenceSet T (fun ω ↦ h ω) := by
  change koopmanL2 hT h = h at hh
  have horbit : ∀ᵐ ω ∂μ, ∀ n : ℕ, h (T^[n] ω) = h ω := by
    rw [ae_all_iff]
    intro n
    have hcoe := Lp.coeFn_compMeasurePreserving h (hT.iterate n)
    rw [← iterate_koopmanL2_apply hT n h, IsFixedPt.iterate hh n] at hcoe
    exact hcoe.symm
  filter_upwards [horbit] with ω hω
  refine mem_birkhoffConvergenceSet_iff.mpr ⟨h ω, ?_⟩
  apply tendsto_const_nhds.congr'
  filter_upwards [eventually_ne_atTop 0] with n hn
  simp only [birkhoffAverage, birkhoffSum]
  have hsum :
      (∑ j ∈ Finset.range n, h (T^[j] ω)) =
        ∑ _j ∈ Finset.range n, h ω := by
    apply Finset.sum_congr rfl
    intro j _hj
    exact hω j
  rw [hsum]
  simp [hn]

/-- A simple-function Koopman coboundary has almost everywhere convergent
Birkhoff averages.  Mathlib's chosen simple representative has finite, hence
bounded, range, so the raw coboundary averages telescope pointwise to zero. -/
theorem ae_mem_birkhoffConvergenceSet_of_mem_simpleKoopmanCoboundarySetL2
    (hT : MeasurePreserving T μ μ) {c : Lp ℝ 2 μ}
    (hc : c ∈ simpleKoopmanCoboundarySetL2 hT) :
    ∀ᵐ ω ∂μ, ω ∈ birkhoffConvergenceSet T (fun ω ↦ c ω) := by
  rcases hc with ⟨u, hu, rfl⟩
  let us : Lp.simpleFunc ℝ 2 μ := ⟨u, hu⟩
  let v : MeasureTheory.SimpleFunc Ω ℝ :=
    Lp.simpleFunc.toSimpleFunc us
  have hv_ae : (fun ω ↦ v ω) =ᵐ[μ] fun ω ↦ u ω := by
    exact Lp.simpleFunc.toSimpleFunc_eq_toFun us
  have hv_comp_ae : (fun ω ↦ v (T ω)) =ᵐ[μ]
      fun ω ↦ u (T ω) := by
    exact hT.quasiMeasurePreserving.ae_eq_comp hv_ae
  have hkoop_ae : (fun ω ↦ koopmanL2 hT u ω) =ᵐ[μ]
      fun ω ↦ u (T ω) := by
    exact Lp.coeFn_compMeasurePreserving u hT
  have hc_ae : (fun ω ↦ koopmanCoboundaryL2 hT u ω) =ᵐ[μ]
      fun ω ↦ v (T ω) - v ω := by
    filter_upwards [Lp.coeFn_sub (koopmanL2 hT u) u,
      hkoop_ae, hv_comp_ae, hv_ae] with ω hsub hkoop hvcomp hv
    simp only [koopmanCoboundaryL2, sub_apply, one_apply_eq_self]
    rw [hsub]
    simp only [Pi.sub_apply]
    rw [hkoop, ← hvcomp, ← hv]
  have hraw : ∀ ω, ω ∈
      birkhoffConvergenceSet T (fun x ↦ v (T x) - v x) := by
    intro ω
    exact mem_birkhoffConvergenceSet_iff.mpr
      ⟨0, tendsto_birkhoffAverage_forwardCoboundary v
        v.finite_range.isBounded ω⟩
  have hevents := birkhoffConvergenceSet_ae_eq_of_ae_eq
    hT.quasiMeasurePreserving hc_ae
  filter_upwards [hevents] with ω hω
  change birkhoffConvergenceSet T
    (fun ω ↦ koopmanCoboundaryL2 hT u ω) ω
  rw [hω]
  exact hraw ω

omit [MeasurableSpace Ω] in
private theorem mem_birkhoffConvergenceSet_add
    {g k : Ω → ℝ} {ω : Ω}
    (hg : ω ∈ birkhoffConvergenceSet T g)
    (hk : ω ∈ birkhoffConvergenceSet T k) :
    ω ∈ birkhoffConvergenceSet T (fun x ↦ g x + k x) := by
  obtain ⟨cg, hcg⟩ := mem_birkhoffConvergenceSet_iff.mp hg
  obtain ⟨ck, hck⟩ := mem_birkhoffConvergenceSet_iff.mp hk
  refine mem_birkhoffConvergenceSet_iff.mpr ⟨cg + ck, ?_⟩
  change Tendsto (fun n ↦ birkhoffAverage ℝ T (g + k) n ω)
    atTop (nhds (cg + ck))
  simpa only [birkhoffAverage_add, Pi.add_apply] using hcg.add hck

/-- Every vector in the fixed-plus-simple-coboundary core has almost
everywhere convergent pointwise Birkhoff averages.  Together with
`dense_fixedPlusSimpleCoboundarySetL2`, this supplies the dense pointwise-good
class needed by the later weak-maximal closure argument. -/
theorem ae_mem_birkhoffConvergenceSet_of_mem_fixedPlusSimpleCoboundarySetL2
    (hT : MeasurePreserving T μ μ) {f : Lp ℝ 2 μ}
    (hf : f ∈ fixedPlusSimpleCoboundarySetL2 hT) :
    ∀ᵐ ω ∂μ, ω ∈ birkhoffConvergenceSet T (fun ω ↦ f ω) := by
  rcases hf with ⟨h, hh, c, hc, rfl⟩
  have hhgood :=
    ae_mem_birkhoffConvergenceSet_of_mem_koopmanFixedSubspaceL2 hT hh
  have hcgood :=
    ae_mem_birkhoffConvergenceSet_of_mem_simpleKoopmanCoboundarySetL2 hT hc
  have hpointwise : ∀ᵐ ω ∂μ, ω ∈
      birkhoffConvergenceSet T (fun x ↦ h x + c x) := by
    filter_upwards [hhgood, hcgood] with ω hhω hcω
    exact mem_birkhoffConvergenceSet_add hhω hcω
  have hadd : (fun ω ↦ (h + c) ω) =ᵐ[μ]
      fun ω ↦ h ω + c ω := by
    exact Lp.coeFn_add h c
  have hevents := birkhoffConvergenceSet_ae_eq_of_ae_eq
    hT.quasiMeasurePreserving hadd
  filter_upwards [hevents, hpointwise] with ω hω hmem
  change birkhoffConvergenceSet T (fun ω ↦ (h + c) ω) ω
  rw [hω]
  exact hmem

section BoundaryProbes

omit [MeasurableSpace Ω] in
/-- The raw endpoint identity includes the totalized horizon-zero value. -/
example (u : Ω → ℝ) (ω : Ω) :
    birkhoffAverage ℝ T (fun x ↦ u (T x) - u x) 0 ω = 0 := by
  simp [birkhoffAverage, birkhoffSum]

omit [MeasurableSpace Ω] in
/-- A constant potential generates the zero coboundary, hence zero averages. -/
example (a : ℝ) (ω : Ω) :
    Tendsto (fun n ↦ birkhoffAverage ℝ T
      (fun _ ↦ a - a) n ω) atTop (nhds 0) := by
  simpa using tendsto_birkhoffAverage_forwardCoboundary
    (T := T) (fun _ : Ω ↦ a) (Set.finite_range_const.isBounded) ω

/-- Identity dynamics give the identity Koopman operator. -/
example (f : Lp ℝ 2 μ) :
    koopmanL2 (MeasurePreserving.id μ) f = f := by
  exact Lp.ext (Lp.coeFn_compMeasurePreserving f (MeasurePreserving.id μ))

/-- Identity dynamics give the zero Koopman coboundary operator. -/
example : koopmanCoboundaryL2 (MeasurePreserving.id μ) =
    (0 : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ) := by
  rw [koopmanCoboundaryL2]
  ext f
  simp [koopmanL2]

/-- Identity dynamics project every `L²` vector to itself. -/
example (f : Lp ℝ 2 μ) :
    koopmanInvariantProjectionL2 (MeasurePreserving.id μ) f = f := by
  change ((koopmanL2 (MeasurePreserving.id μ)).eqLocus
    (1 : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ)).starProjection f = f
  rw [Submodule.starProjection_eq_self_iff]
  change koopmanL2 (MeasurePreserving.id μ) f = f
  exact Lp.ext (Lp.coeFn_compMeasurePreserving f (MeasurePreserving.id μ))

/-- Every chosen representative is pointwise-good under identity dynamics. -/
example (f : Lp ℝ 2 μ) :
    ∀ᵐ ω ∂μ, ω ∈ birkhoffConvergenceSet id (fun ω ↦ f ω) := by
  apply ae_mem_birkhoffConvergenceSet_of_mem_koopmanFixedSubspaceL2
    (MeasurePreserving.id μ)
  change koopmanL2 (MeasurePreserving.id μ) f = f
  exact Lp.ext (Lp.coeFn_compMeasurePreserving f (MeasurePreserving.id μ))

/-- The zero-measure boundary has zero, not unit, Koopman operator norm. -/
example (hT : MeasurePreserving T (0 : Measure Ω) (0 : Measure Ω)) :
    ‖koopmanL2 hT‖ = 0 := by
  have hzero : koopmanL2 hT = 0 := by
    ext f
    rw [ae_zero]
    exact Filter.eventually_bot
  rw [hzero, norm_zero]

/-- Generic `L²` norm convergence directly supplies an almost-everywhere
convergent subsequence, not a theorem about the full pointwise sequence. -/
example {f : ℕ → Lp ℝ 2 μ} {g : Lp ℝ 2 μ}
    (hfg : Tendsto f atTop (nhds g)) :
    ∃ ns : ℕ → ℕ, StrictMono ns ∧
      ∀ᵐ ω ∂μ, Tendsto (fun i ↦ f (ns i) ω) atTop (nhds (g ω)) := by
  exact (tendstoInMeasure_of_tendsto_Lp hfg).exists_seq_tendsto_ae

/-- Integer translation on counting measure exercises density and the
pointwise-good core on an infinite-measure, non-probability base. -/
example :
    let hT : MeasurePreserving (fun z : ℤ ↦ z + 1)
        (Measure.count : Measure ℤ) Measure.count := by
      simpa only using
        measurePreserving_add_right (Measure.count : Measure ℤ) 1
    Dense (fixedPlusSimpleCoboundarySetL2 hT) ∧
      ∀ {f : Lp ℝ 2 (Measure.count : Measure ℤ)},
        f ∈ fixedPlusSimpleCoboundarySetL2 hT →
          ∀ᵐ z ∂(Measure.count : Measure ℤ),
            z ∈ birkhoffConvergenceSet (fun z : ℤ ↦ z + 1)
              (fun z ↦ f z) := by
  dsimp only
  let hT : MeasurePreserving (fun z : ℤ ↦ z + 1)
      (Measure.count : Measure ℤ) Measure.count := by
    simpa only using
      measurePreserving_add_right (Measure.count : Measure ℤ) 1
  refine ⟨dense_fixedPlusSimpleCoboundarySetL2 hT, ?_⟩
  intro f hf
  exact ae_mem_birkhoffConvergenceSet_of_mem_fixedPlusSimpleCoboundarySetL2
    hT hf

/-- A noninjective constant map can preserve a Dirac measure, so the API does
not smuggle in invertibility. -/
example :
    ∃ (T : Bool → Bool)
      (hT : MeasurePreserving T (Measure.dirac false) (Measure.dirac false)),
      ¬ Function.Injective T ∧
        ∀ {f : Lp ℝ 2 (Measure.dirac false)},
          f ∈ fixedPlusSimpleCoboundarySetL2 hT →
            ∀ᵐ ω ∂Measure.dirac false,
              ω ∈ birkhoffConvergenceSet T (fun ω ↦ f ω) := by
  let T : Bool → Bool := fun _ ↦ false
  have hTnotinj : ¬ Function.Injective T := by
    intro hTinj
    have : (false : Bool) = true := hTinj rfl
    simp at this
  have hTpres :
      MeasurePreserving T (Measure.dirac false) (Measure.dirac false) := by
    refine ⟨measurable_const, ?_⟩
    rw [Measure.map_dirac' measurable_const]
  refine ⟨T, hTpres, hTnotinj, ?_⟩
  intro f hf
  exact ae_mem_birkhoffConvergenceSet_of_mem_fixedPlusSimpleCoboundarySetL2
    hTpres hf

/-- A simple `L²` vector exposes an almost-everywhere equal, finite-range,
hence bounded, representative. -/
example (u : Lp.simpleFunc ℝ 2 μ) :
    ∃ v : MeasureTheory.SimpleFunc Ω ℝ,
      (fun ω ↦ v ω) =ᵐ[μ] (fun ω ↦ (u : Lp ℝ 2 μ) ω) ∧
        Bornology.IsBounded (Set.range v) := by
  refine ⟨Lp.simpleFunc.toSimpleFunc u, ?_, ?_⟩
  · exact Lp.simpleFunc.toSimpleFunc_eq_toFun u
  · exact (Lp.simpleFunc.toSimpleFunc u).finite_range.isBounded

end BoundaryProbes

#print axioms tendsto_birkhoffAverage_forwardCoboundary
#print axioms dense_fixedPlusSimpleCoboundarySetL2
#print axioms tendsto_birkhoffAverage_koopmanL2_projection
#print axioms exists_subsequence_ae_tendsto_birkhoffAverage_koopmanL2_projection
#print axioms ae_mem_birkhoffConvergenceSet_of_mem_fixedPlusSimpleCoboundarySetL2

end NonlinearDynamics.Random.RandomCocycles
